
<!-- HEADER -->
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <title>Pokédex</title>

        <link rel="stylesheet" href="/main.css" />
        <script src="https://kit.fontawesome.com/aac8485983.js" crossorigin="anonymous"></script>
        <script
		  src="https://code.jquery.com/jquery-3.4.1.min.js"
		  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
		  crossorigin="anonymous"></script>
    </head>
    <body>
    	<div class="header-container">
    		<div class="center-wrap">
    			<h1 class="header-title">Pokédex</h1>
    			<div class="search-form">
    				<input class="search-input" id="search" placeholder="Search..."/> 
    			</div>
    		</div>
    	</div>
    	<div class="pokemon-container">
    		<div class="container">
	    		<div class="row">
